### ISSUE TITLE
size mismatch  in loading state_dict for STDiT

### ISSUE THREAD

**Issue by Jianrong-Lu** [hpcaitech/Open-Sora#142]
Traceback (most recent call last):
  File "/home/lu_24/Open-Sora/scripts/inference.py", line 121, in <module>
    main()
  File "/home/lu_24/Open-Sora/scripts/inference.py", line 67, in main
    model = build_module(
  File "/home/lu_24/anaconda3/envs/opensora/lib/python3.10/site-packages/opensora/registry.py", line 22, in build_module
    return builder.build(cfg)
  File "/home/lu_24/anaconda3/envs/opensora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/lu_24/anaconda3/envs/opensora/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/lu_24/anaconda3/envs/opensora/lib/python3.10/site-packages/opensora/models/stdit/stdit.py", line 387, in STDiT_XL_2
    load_checkpoint(model, from_pretrained)
  File "/home/lu_24/anaconda3/envs/opensora/lib/python3.10/site-packages/opensora/utils/ckpt_utils.py", line 206, in load_checkpoint
    missing_keys, unexpected_keys = model.load_state_dict(state_dict, strict=False)
  File "/home/lu_24/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for STDiT:
        size mismatch for x_embedder.proj.weight: copying a param with shape torch.Size([1152, 4, 2, 2]) from checkpoint, the shape in current model is torch.Size([1152, 4, 1, 2, 2]).

**Comment by geng-m** [comment]
maybe the answer lying [here](https://github.com/hpcaitech/Open-Sora/blob/main/opensora/utils/ckpt_utils.py#L35)
