### ISSUE TITLE
cannot import name 'AutoencoderKLTemporalDecoder' from 'diffusers.models'

### ISSUE THREAD

**Issue by zj19941113** [hpcaitech/Open-Sora#149]
![2024-03-19](https://github.com/hpcaitech/Open-Sora/assets/41109686/be840954-2744-4149-aaf2-a6e45861595d)
when i run
`torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path /shareData/visual_models/open-sora/OpenSora-v1-HQ-16x512x512.pth`

```
ImportError: cannot import name 'AutoencoderKLTemporalDecoder' from 'diffusers.models' (/usr/local/lib/python3.10/dist-packages/diffusers/models/__init__.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1356) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/inference.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-19_11:53:55
  host      : Super-Server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1356)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by yjdqk** [comment]
you can try to update the diffusers package to 0.26.0+ to solve the problem
