### ISSUE TITLE
RuntimeError: Could not find 'RANK' in the torch environment

### ISSUE THREAD

**Issue by zzw8969** [hpcaitech/Open-Sora#194]
(opensora) zhouyf@zhouyf-System-Product-Name:~/Open-Sora$ python -m scripts.inference configs/dit/inference/1x256x256-class.py
/home/zhouyf/anaconda3/envs/opensora/lib/python3.10/site-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
/home/zhouyf/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
  warnings.warn(
Config (path: configs/dit/inference/1x256x256-class.py): {'num_frames': 1, 'fps': 1, 'image_size': (256, 256), 'model': {'type': 'DiT-XL/2', 'no_temporal_pos_emb': True, 'condition': 'label_1000', 'from_pretrained': 'DiT-XL-2-256x256.pt'}, 'vae': {'type': 'VideoAutoencoderKL', 'from_pretrained': 'stabilityai/sd-vae-ft-ema'}, 'text_encoder': {'type': 'classes', 'num_classes': 1000}, 'scheduler': {'type': 'dpm-solver', 'num_sampling_steps': 20, 'cfg_scale': 4.0}, 'dtype': 'fp16', 'batch_size': 2, 'seed': 42, 'prompt_path': './assets/texts/imagenet_id.txt', 'save_dir': './outputs/samples/', 'multi_resolution': False}
Traceback (most recent call last):
  File "/home/zhouyf/anaconda3/envs/opensora/lib/python3.10/site-packages/colossalai/initialize.py", line 163, in launch_from_torch
    rank = int(os.environ["RANK"])
  File "/home/zhouyf/anaconda3/envs/opensora/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by zzw8969** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhouyf/anaconda3/envs/opensora/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhouyf/anaconda3/envs/opensora/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zhouyf/Open-Sora/scripts/inference.py", line 112, in <module>
    main()
  File "/home/zhouyf/Open-Sora/scripts/inference.py", line 30, in main
    colossalai.launch_from_torch({})
  File "/home/zhouyf/anaconda3/envs/opensora/lib/python3.10/site-packages/colossalai/initialize.py", line 169, in launch_from_torch
    raise RuntimeError(
RuntimeError: Could not find 'RANK' in the torch environment, visit https://www.colossalai.org/ for more information on launching with torch

**Comment by zhengzangw** [comment]
You should not run inference like `python -m scripts.inference`. Please check our inference instruction [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#inference). Always run with `torchrun`.
