### ISSUE TITLE
I cannot install the requirements.txt

### ISSUE THREAD

**Issue by Rieuxx** [hpcaitech/Open-Sora#220]
im not so experienced but im downloading the req with "pip install -r requirements.txt". Im using git bash and files were downloaded by zip. Thats at my desktop. And im getting that problem:
`bilgi@DESKTOP-E0LBN93 MINGW64 ~/Desktop/Open-Sora-main
$ pip install -r requirements.txt
Collecting colossalai (from -r requirements.txt (line 1))
  Using cached colossalai-0.3.6.tar.gz (1.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [20 lines of output]
  Traceback (most recent call last):
    File "C:\Users\bilgi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\bilgi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\bilgi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\bilgi\AppData\Local\Temp\pip-build-env-1hxg0ira\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\bilgi\AppData\Local\Temp\pip-build-env-1hxg0ira\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\bilgi\AppData\Local\Temp\pip-build-env-1hxg0ira\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\bilgi\AppData\Local\Temp\pip-build-env-1hxg0ira\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 20, in <module>
  RuntimeError: Windows is not supported yet. Please try again within the Windows Subsystem for Linux (WSL).
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by Rieuxx** [comment]
Okay i got it it supports just linux. isnt it? if theres an any idea im waiting here and not closing issue.

**Comment by MiletaA** [comment]
Try by running wsl --install in powershell as administrator and restart computer. That command should enable features of ubuntu terminal. After installing try with pip3 install -r requirements.txt (should work if everything is installed if not run sudo apt update
sudo apt install python3 python3-pip
)

**Comment by Rieuxx** [comment]
> Try by running wsl --install in powershell as administrator and restart computer. That command should enable features of ubuntu terminal. After installing try with pip3 install -r requirements.txt (should work if everything is installed if not run sudo apt update sudo apt install python3 python3-pip )

thanks that feedback. I did them and installed ubuntu today. But i didnt understand how can i go directory which is in my local pc? And cause of that i cant install requirement(because i cant the directory which has requirement). Can you or someone help me please?
