### ISSUE TITLE
执行训练的时候报错，怎么问题怎么解决？

### ISSUE THREAD

**Issue by findlyhl** [hpcaitech/Open-Sora#32]
torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
/root/miniconda3/lib/python3.10/site-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel
  warnings.warn("Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel")
unable to import lightllm kernels
Traceback (most recent call last):
  File "/root/autodl-tmp/Open-Sora/train.py", line 29, in <module>
    from open_sora.modeling import DiT_models
  File "/root/autodl-tmp/Open-Sora/open_sora/modeling/__init__.py", line 2, in <module>
    from .latte import LatteT2V
  File "/root/autodl-tmp/Open-Sora/open_sora/modeling/latte/__init__.py", line 1, in <module>
    from .latte_t2v import LatteT2V
  File "/root/autodl-tmp/Open-Sora/open_sora/modeling/latte/latte_t2v.py", line 12, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (/root/miniconda3/lib/python3.10/site-packages/diffusers/models/embeddings.py)
[2024-03-05 20:52:11,607] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 42774) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.2+cu121', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/root/autodl-tmp/Open-Sora/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-05_20:52:11
  host      : autodl-container-929b4da753-1a924379
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 42774)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by ver217** [comment]
Please downgrad diffusers. Try `pip install diffusers==0.24.0`

**Comment by findlyhl** [comment]
多谢，问题解决
