### ISSUE TITLE
What cause this error in training?

### ISSUE THREAD

**Issue by Weixiang-Sun** [hpcaitech/Open-Sora#418]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'height'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/opensora/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/miniconda3/envs/opensora/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandarallel/core.py", line 95, in __call__
    result = self.work_function(
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandarallel/data_types/dataframe.py", line 32, in work
    return data.apply(
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/datasets/sampler.py", line 20, in apply
    data["height"],
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'height'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Opensora-1.1/scripts/train.py", line 322, in <module>
    main()
  File "/root/Opensora-1.1/scripts/train.py", line 186, in main
    num_steps_per_epoch = dataloader.batch_sampler.get_num_batch() // dist.get_world_size()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/datasets/sampler.py", line 77, in get_num_batch
    bucket_sample_dict = self.group_by_bucket()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/datasets/sampler.py", line 56, in group_by_bucket
    bucket_ids = self.dataset.data.parallel_apply(
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandarallel/core.py", line 333, in closure
    results_promise.get()
  File "/root/miniconda3/envs/opensora/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
KeyError: 'height'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'height'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/opensora/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/miniconda3/envs/opensora/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandarallel/core.py", line 95, in __call__
    result = self.work_function(
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandarallel/data_types/dataframe.py", line 32, in work
    return data.apply(
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/datasets/sampler.py", line 20, in apply
    data["height"],
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'height'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Opensora-1.1/scripts/train.py", line 322, in <module>
    main()
  File "/root/Opensora-1.1/scripts/train.py", line 186, in main
    num_steps_per_epoch = dataloader.batch_sampler.get_num_batch() // dist.get_world_size()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/datasets/sampler.py", line 77, in get_num_batch
    bucket_sample_dict = self.group_by_bucket()
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/datasets/sampler.py", line 56, in group_by_bucket
    bucket_ids = self.dataset.data.parallel_apply(
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/pandarallel/core.py", line 333, in closure
    results_promise.get()
  File "/root/miniconda3/envs/opensora/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
KeyError: 'height'
[2024-05-26 19:58:25,587] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3060525) of binary: /root/miniconda3/envs/opensora/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/opensora/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-26_19:58:25
  host      : LUCAS-DEV-fffd8d
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3060526)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-26_19:58:25
  host      : LUCAS-DEV-fffd8d
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3060525)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by fenghe12** [comment]
请问您解决了吗 我遇到了相同的错误

**Comment by CaptainDP** [comment]
I had the same problem


[2024-07-29 10:30:40] Building dataset...
[2024-07-29 10:30:40] Dataset contains 3 samples.
[2024-07-29 10:30:40] Number of buckets: 1025
INFO: Pandarallel will run on 16 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
[2024-07-29 10:30:40] Building buckets...
[rank0]: multiprocessing.pool.RemoteTraceback: 
[rank0]: """
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/conda/envs/opens/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
[rank0]:     return self._engine.get_loc(casted_key)
[rank0]:   File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
[rank0]:   File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
[rank0]:   File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
[rank0]:   File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
[rank0]: KeyError: 'height'

**Comment by g-jing** [comment]
Still the same issue. Anyone has a solution now?

**Comment by hustzxl** [comment]
me too
