### ISSUE TITLE
runtime error on HF space

### ISSUE THREAD

**Issue by coding-garden-1** [hpcaitech/Open-Sora#420]
may 29 2024:
runtime error
Space failed. Exit code: 1. Reason: ise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 306, in <module>
    def run_inference(mode, prompt_text, resolution, length, reference_image):
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/decorator.py", line 111, in _GPU
    client.startup_report()
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/client.py", line 39, in startup_report
    while (status := client.startup_report()) is httpx.codes.NOT_FOUND: # pragma: no cover
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/api.py", line 80, in startup_report
    res = self.client.post('/startup-report')
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1145, in post
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

Container logs:

===== Application Startup at 2024-05-21 07:52:20 =====

Collecting flash-attn
  Downloading flash_attn-2.5.8.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 52.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started

**Comment by JThh** [comment]
Can you check if this is runnable `ping -c 4 google.com`?

**Comment by zhengzangw** [comment]
Please try with OpenSora 1.2.
