### ISSUE TITLE
No such file or directory: '/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/extensions/pybind/optimizer/optimizer.cpp'

### ISSUE THREAD

**Issue by yiiizuo** [hpcaitech/Open-Sora#429]
Traceback (most recent call last):
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/extensions/cpp_extension.py", line 132, in load
    op_kernel = self.import_op()
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/extensions/cpp_extension.py", line 61, in import_op
    return importlib.import_module(self.prebuilt_import_path)
  File "/opt/conda/envs/opensora/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'colossalai._C.fused_optim_cuda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zuoyi/T2V/Code/Open-Sora/scripts/train.py", line 329, in <module>
    main()
  File "/zuoyi/T2V/Code/Open-Sora/scripts/train.py", line 163, in main
    optimizer = HybridAdam(
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/nn/optimizer/hybrid_adam.py", line 88, in __init__
    fused_optim = FusedOptimizerLoader().load()
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/kernel_loader.py", line 83, in load
    return usable_exts[0].load()
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/extensions/cpp_extension.py", line 136, in load
    op_kernel = self.build_jit()
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/extensions/cuda_extension.py", line 86, in build_jit
    op_kernel = load(
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1669, in _jit_compile
    version = JIT_EXTENSION_VERSIONER.bump_version_if_changed(
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/torch/utils/_cpp_extension_versioner.py", line 45, in bump_version_if_changed
    hash_value = hash_source_files(hash_value, source_files)
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/torch/utils/_cpp_extension_versioner.py", line 15, in hash_source_files
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/extensions/pybind/optimizer/optimizer.cpp'

Process finished with exit code 1

**Comment by fenghe12** [comment]
you need to build colossalai from source code，otherwise such error will occur

**Comment by fenghe12** [comment]
不能直接用pip 安装 你去看一下colossalai官方的安装指引

**Comment by yiiizuo** [comment]
Thank you for your reply. Then, when I build colossalai from source code, the following issues occurred:
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/booster/__init__.py", line 2, in <module>
    from .booster import Booster
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/booster/booster.py", line 26, in <module>
    from .plugin import Plugin
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/booster/plugin/__init__.py", line 1, in <module>
    from .gemini_plugin import GeminiPlugin
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/booster/plugin/gemini_plugin.py", line 30, in <module>
    from colossalai.shardformer import ShardConfig, ShardFormer
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/shardformer/__init__.py", line 1, in <module>
    from .shard import GradientCheckpointConfig, ModelSharder, PipelineGradientCheckpointConfig, ShardConfig, ShardFormer
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/shardformer/shard/__init__.py", line 3, in <module>
    from .sharder import ModelSharder
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/shardformer/shard/sharder.py", line 10, in <module>
    from ..policies.auto_policy import get_autopolicy
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/shardformer/policies/auto_policy.py", line 6, in <module>
    from .base_policy import Policy
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/shardformer/policies/base_policy.py", line 13, in <module>
    from ..layer.normalization import BaseLayerNorm
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/shardformer/layer/__init__.py", line 2, in <module>
    from .attn import AttnMaskType, ColoAttention
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/shardformer/layer/attn.py", line 7, in <module>
    from colossalai.kernel.kernel_loader import (
  File "/opt/conda/envs/opensora/lib/python3.10/site-packages/colossalai/kernel/kernel_loader.py", line 4, in <module>
    from .extensions import (
ModuleNotFoundError: No module named 'colossalai.kernel.extensions'

Process finished with exit code 1

**Comment by JThh** [comment]
Can you refer to [this issue](https://github.com/hpcaitech/ColossalAI/issues/5458), and when installing from source, you pull from main branch?

**Comment by JThh** [comment]
Let me know if this issue persists after doing so.

**Comment by aulaywang** [comment]
I meet the similar problem

**Comment by aulaywang** [comment]
I use the `pip install colossalai==0.3.6 ` and this problem seems to be solved.

**Comment by fenghe12** [comment]
you need to build colossalai from source code，otherwise such error will occur

**Comment by aulaywang** [comment]
> you need to build colossalai from source code，otherwise such error will occur

Do you have tutorials or commands about the building process? I tried several times but failed.

**Comment by ver217** [comment]
Hi, `colossalai==0.3.6` and `colossalai==0.3.9` are both OK.
