### ISSUE TITLE
training 1.2 stuck

### ISSUE THREAD

**Issue by oceanogeology** [hpcaitech/Open-Sora#637]
Often stuck in any number of traing step, and cuda usage is 0.
![image](https://github.com/user-attachments/assets/46aa853a-490f-419e-bed9-e6dd176c2340)
![image](https://github.com/user-attachments/assets/355b31a0-2099-40bd-82cf-77132f3ff15c)

**Comment by oceanogeology** [comment]
Epoch 0:  19%|██████▏                          | 1610/8573 [11:25:45<50:22:32, 26.05s/it, loss=0.279, step=1609, global_step=1609]
Traceback (most recent call last):
  File "Open-Sora1.2/scripts/train.py", line 454, in <module>
    main()
  File "Open-Sora1.2/scripts/train.py", line 350, in main
    booster.backward(loss=loss, optimizer=optimizer)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/colossalai/booster/booster.py", line 176, in backward
    optimizer.backward(loss)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/colossalai/zero/low_level/low_level_optim.py", line 536, in backward
    loss.backward(retain_graph=retain_graph)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/colossalai/zero/low_level/low_level_optim.py", line 272, in grad_handl
er
    LowLevelZeroOptimizer.add_to_bucket(param, group_id, bucket_store, param_store, grad_store)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/colossalai/zero/low_level/low_level_optim.py", line 519, in add_to_buc
ket
    LowLevelZeroOptimizer.run_reduction(bucket_store, grad_store)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/colossalai/zero/low_level/low_level_optim.py", line 297, in run_reduct
ion
    bucket_store.build_grad_in_bucket()
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/colossalai/zero/low_level/bookkeeping/bucket_store.py", line 106, in b
uild_grad_in_bucket
    grad_current_rank = grad_list[rank].clone().detach()
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
[E ProcessGroupNCCL.cpp:916] [Rank 6] NCCL watchdog thread terminated with exception: CUDA error: uncorrectable ECC error encounte
red
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /opt/conda/conda-bld/pytorch_1702400412039/work/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f8bfad77617 in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f8bfad3298d in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f8bfae34128 in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x80 (0x7f8bfbda8ef0 in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x7f8bfbdacd18 in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x250 (0x7f8bfbdc35b0 in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x78 (0x7f8bfbdc38b8 in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdbbf4 (0x7f8c480c8bf4 in /opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #8: <unknown function> + 0x8609 (0x7f8c89a48609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #9: clone + 0x43 (0x7f8c89813133 in /usr/lib/x86_64-linux-gnu/libc.so.6)

[2024-07-29 04:49:55,282] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4063168 closing signal SIGTERM
[2024-07-29 04:49:55,283] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4063169 closing signal SIGTERM
[2024-07-29 04:49:55,283] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4063170 closing signal SIGTERM
[2024-07-29 04:49:55,284] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4063171 closing signal SIGTERM
[2024-07-29 04:49:55,284] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4063172 closing signal SIGTERM
[2024-07-29 04:49:55,285] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4063173 closing signal SIGTERM
[2024-07-29 04:49:55,285] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4063175 closing signal SIGTERM
[2024-07-29 04:50:02,533] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 6 (pid: 4063174) of binary: /opt/conda/envs/pytorch/bin/python
