### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by SamitM1** [hpcaitech/Open-Sora#663]
I receive the following error while trying to train Open-Sora1.2 , my data is stored on an AWS vm with 16tb of EBS storage and I have mounted it to my vm on lambda.  Do I need more storage than 16tb when my data is only 5tb or is this a bug? 

```
[2024-08-10 02:11:44] Building dataset...
[2024-08-10 02:12:19] Dataset contains 432801 samples.
[2024-08-10 02:12:19] Number of buckets: 626
INFO: Pandarallel will run on 16 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
[2024-08-10 02:12:19] Building buckets...
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/pandarallel/core.py", line 263, in closure
    pickle.dump(chunk, filedescriptor)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/Open-Sora/scripts/train.py", line 412, in <module>
    main()
  File "/workspace/Open-Sora/scripts/train.py", line 111, in main
    numsteps_per_epoch = len(dataloader)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 483, in __len
    return len(self.indexsampler)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/opensora/datasets/sampler.py", line 191, in __len
    return self.get_num_batch() // dist.get_world_size()
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/opensora/datasets/sampler.py", line 221, in get_num_batch
    bucket_sample_dict = self.group_by_bucket()
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/opensora/datasets/sampler.py", line 200, in group_by_bucket
    bucket_ids = self.dataset.data.parallel_apply(
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/pandarallel/core.py", line 263, in closure
    pickle.dump(chunk, file_descriptor)
OSError: [Errno 28] No space left on device
[2024-08-10 02:12:23,758] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 44) of binary: /opt/conda/envs/pytorch/bin/python
```

Would greatly appreciate some help with this.

**Comment by cyz6668** [comment]
I have the same problem.Did you solve it?
