### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by lweingart** [hpcaitech/Open-Sora#664]
Hi guys,

Thank you very much for sharing your work, it's awesome.
I'm trying to prepare my dataset, following the steps described [here](https://github.com/hpcaitech/Open-Sora/blob/main/docs/data_processing.md), but at the step "3.1 Predict aesthetic scores", after 64% of the progess bar I get the following error: `RuntimeError: Model has been downloaded but the SHA256 checksum does not not match`

Did you change a model without updating the checksum, or is there another kind of issue, do you think ?

Command:
```
!torchrun --nproc_per_node 1 -m tools.scoring.aesthetic.inference \
  {ROOT_META}/meta_clips_info_fmin1.csv \
  --bs 256 \
  --num_workers 1
```

Full trace:
```
64%|█████████████████████████▍              | 566M/890M [18:38<10:39, 531kiB/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/content/drive/MyDrive/Open-Sora/opensora/tools/scoring/aesthetic/inference.py", line 214, in <module>
[rank0]:     main()
[rank0]:   File "/content/drive/MyDrive/Open-Sora/opensora/tools/scoring/aesthetic/inference.py", line 150, in main
[rank0]:     model = AestheticScorer(768, device)
[rank0]:   File "/content/drive/MyDrive/Open-Sora/opensora/tools/scoring/aesthetic/inference.py", line 107, in __init__
[rank0]:     self.clip, self.preprocess = clip.load("ViT-L/14", device=device)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/clip/clip.py", line 120, in load
[rank0]:     model_path = _download(_MODELS[name], download_root or os.path.expanduser("~/.cache/clip"))
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/clip/clip.py", line 70, in _download
[rank0]:     raise RuntimeError("Model has been downloaded but the SHA256 checksum does not not match")
[rank0]: RuntimeError: Model has been downloaded but the SHA256 checksum does not not match
E0810 12:00:01.454000 132123888685056 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 13521) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools.scoring.aesthetic.inference FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-10_12:00:01
  host      : 0679decb4699
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13521)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Any help would be greatly appreciated.
Thank you very much in advance :-)

Cheers

**Comment by lweingart** [comment]
Hi again,

Sorry, I realised the error does not come from one of your models, but from openai CLIP.
Thanks again for you work
