### ISSUE TITLE
NotImplementedError: This is a project in development

### ISSUE THREAD

**Issue by lxrswdd** [hpcaitech/Open-Sora#670]
Hello
I got the following error.
`(opensora) assa8945@ubco-csl-105751:~/video_generators/Open-Sora$ python scripts/inference.py configs/opensora-v1-2/inference/sample.py   --num-frames 4s --resolution 720p --aspect-ratio 9:16   --num-sampling-steps 30 --flow 5 --aes 6.5   --prompt "a beautiful waterfall"
Traceback (most recent call last):
  File "/home/assa8945/video_generators/Open-Sora/scripts/inference.py", line 9, in <module>
    from mmengine.runner import set_random_seed
ModuleNotFoundError: No module named 'mmengine'

(opensora) assa8945@ubco-csl-105751:~/video_generators/Open-Sora$ pip install mmengine==0.0.1rc0
Collecting mmengine==0.0.1rc0
  Downloading mmengine-0.0.1rc0-py3-none-any.whl.metadata (370 bytes)
Downloading mmengine-0.0.1rc0-py3-none-any.whl (2.0 kB)
Installing collected packages: mmengine
Successfully installed mmengine-0.0.1rc0

(opensora) assa8945@ubco-csl-105751:~/video_generators/Open-Sora$ python scripts/inference.py configs/opensora-v1-2/inference/sample.py   --num-frames 4s --resolution 720p --aspect-ratio 9:16   --num-sampling-steps 30 --flow 5 --aes 6.5   --prompt "a beautiful waterfall"
Traceback (most recent call last):
  File "/home/assa8945/video_generators/Open-Sora/scripts/inference.py", line 9, in <module>
    from mmengine.runner import set_random_seed
  File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/mmengine/__init__.py", line 1, in <module>
    raise NotImplementedError('This is a project in development')
NotImplementedError: This is a project in development

(opensora) assa8945@ubco-csl-105751:~/video_generators/Open-Sora$ pip install mmengine
Requirement already satisfied: mmengine in /home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages (0.0.1rc0)

(opensora) assa8945@ubco-csl-105751:~/video_generators/Open-Sora$ python scripts/inference.py configs/opensora-v1-2/inference/sample.py   --num-frames 4s --resolution 720p --aspect-ratio 9:16   --num-sampling-steps 30 --flow 5 --aes 6.5   --prompt "a beautiful waterfall"
Traceback (most recent call last):
  File "/home/assa8945/video_generators/Open-Sora/scripts/inference.py", line 9, in <module>
    from mmengine.runner import set_random_seed
  File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/mmengine/__init__.py", line 1, in <module>
    raise NotImplementedError('This is a project in development')
NotImplementedError: This is a project in development

(opensora) assa8945@ubco-csl-105751:~/video_generators/Open-Sora$ `

**Comment by FlyHighest** [comment]
If you strictly follow the installation instructions in readme, you shouldn't have the issue about mmengine. It's been written in requirements.txt. 
I suggest you rebuild the environment following the docs or check if your current env is the one you installed opensora.

**Comment by lxrswdd** [comment]
@FlyHighest 
I reinstalled it and followed each of the steps and the error occurred at the following step:
```
# install apex
# set enable_layernorm_kernel=False in config to disable apex
```
I also attached the full log file :[opensora_log.log](https://github.com/user-attachments/files/16645119/opensora_log.log)


```
(opensora) assa8945@ubco-csl-105751:~/video_generators/Open-Sora/Open-Sora$ pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" git+https://github.com/NVIDIA/apex.git
Using pip 24.2 from /home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip (python 3.9)
Collecting git+https://github.com/NVIDIA/apex.git
  Cloning https://github.com/NVIDIA/apex.git to /tmp/pip-req-build-_blumxvs
  Running command git version
  git version 2.34.1
  Running command git clone --filter=blob:none https://github.com/NVIDIA/apex.git /tmp/pip-req-build-_blumxvs
  Cloning into '/tmp/pip-req-build-_blumxvs'...
  Updating files:   0% (2/505)
  Updating files:   1% (6/505)
  Updating files:   2% (11/505)
  Updating files:   3% (16/505)
  Updating files:   4% (21/505)
  Updating files:   5% (26/505)
  Updating files:   6% (31/505)
  Updating files:   7% (36/505)
  Updating files:   8% (41/505)
  Updating files:   9% (46/505)
  Updating files:  10% (51/505)
  Updating files:  11% (56/505)
  Updating files:  12% (61/505)
  Updating files:  13% (66/505)
  Updating files:  14% (71/505)
  Updating files:  15% (76/505)
  Updating files:  16% (81/505)
  Updating files:  17% (86/505)
  Updating files:  18% (91/505)
  Updating files:  19% (96/505)
  Updating files:  20% (101/505)
  Updating files:  21% (107/505)
  Updating files:  22% (112/505)
  Updating files:  23% (117/505)
  Updating files:  24% (122/505)
  Updating files:  25% (127/505)
  Updating files:  26% (132/505)
  Updating files:  27% (137/505)
  Updating files:  28% (142/505)
  Updating files:  29% (147/505)
  Updating files:  30% (152/505)
  Updating files:  31% (157/505)
  Updating files:  32% (162/505)
  Updating files:  33% (167/505)
  Updating files:  34% (172/505)
  Updating files:  35% (177/505)
  Updating files:  36% (182/505)
  Updating files:  37% (187/505)
  Updating files:  38% (192/505)
  Updating files:  39% (197/505)
  Updating files:  40% (202/505)
  Updating files:  41% (208/505)
  Updating files:  42% (213/505)
  Updating files:  43% (218/505)
  Updating files:  44% (223/505)
  Updating files:  45% (228/505)
  Updating files:  46% (233/505)
  Updating files:  47% (238/505)
  Updating files:  48% (243/505)
  Updating files:  49% (248/505)
  Updating files:  50% (253/505)
  Updating files:  51% (258/505)
  Updating files:  52% (263/505)
  Updating files:  53% (268/505)
  Updating files:  54% (273/505)
  Updating files:  55% (278/505)
  Updating files:  56% (283/505)
  Updating files:  57% (288/505)
  Updating files:  58% (293/505)
  Updating files:  59% (298/505)
  Updating files:  60% (303/505)
  Updating files:  61% (309/505)
  Updating files:  62% (314/505)
  Updating files:  63% (319/505)
  Updating files:  64% (324/505)
  Updating files:  65% (329/505)
  Updating files:  66% (334/505)
  Updating files:  67% (339/505)
  Updating files:  68% (344/505)
  Updating files:  69% (349/505)
  Updating files:  70% (354/505)
  Updating files:  71% (359/505)
  Updating files:  72% (364/505)
  Updating files:  73% (369/505)
  Updating files:  74% (374/505)
  Updating files:  75% (379/505)
  Updating files:  76% (384/505)
  Updating files:  77% (389/505)
  Updating files:  78% (394/505)
  Updating files:  79% (399/505)
  Updating files:  80% (404/505)
  Updating files:  81% (410/505)
  Updating files:  82% (415/505)
  Updating files:  83% (420/505)
  Updating files:  84% (425/505)
  Updating files:  85% (430/505)
  Updating files:  86% (435/505)
  Updating files:  87% (440/505)
  Updating files:  88% (445/505)
  Updating files:  89% (450/505)
  Updating files:  90% (455/505)
  Updating files:  91% (460/505)
  Updating files:  92% (465/505)
  Updating files:  93% (470/505)
  Updating files:  94% (475/505)
  Updating files:  95% (480/505)
  Updating files:  96% (485/505)
  Updating files:  97% (490/505)
  Updating files:  98% (495/505)
  Updating files:  99% (500/505)
  Updating files: 100% (505/505)
  Updating files: 100% (505/505), done.
  Running command git rev-parse HEAD
  79e3dc48856b8786f95b1bdd219cc6a7d9bddd58
  Resolved https://github.com/NVIDIA/apex.git to commit 79e3dc48856b8786f95b1bdd219cc6a7d9bddd58
  Running command git submodule update --init --recursive -q
  Running command git rev-parse HEAD
  79e3dc48856b8786f95b1bdd219cc6a7d9bddd58
  Running command Preparing metadata (pyproject.toml)

  A module that was compiled using NumPy 1.x cannot be run in
  NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
  versions of NumPy, modules must be compiled with NumPy 2.0.
  Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

  If you are a user of the module, the easiest solution will be to
  downgrade to 'numpy<2' or try to upgrade the affected module.
  We expect that some modules will need time to support NumPy 2.

  Traceback (most recent call last):  File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 10, in <module>
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/__init__.py", line 1477, in <module>
      from .functional import *  # noqa: F403
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/functional.py", line 9, in <module>
      import torch.nn.functional as F
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
      from .modules import *  # noqa: F403
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
      from .transformer import TransformerEncoder, TransformerDecoder, \
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
      device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
  /home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


  torch.__version__  = 2.2.2+cu121


  running dist_info
  creating /tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info
  writing /tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-b8zsyiqo/apex.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-b8zsyiqo/apex-0.1.dist-info'
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: packaging>20.6 in /home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages (from apex==0.1) (24.1)
Building wheels for collected packages: apex
  Running command Building wheel for apex (pyproject.toml)

  A module that was compiled using NumPy 1.x cannot be run in
  NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
  versions of NumPy, modules must be compiled with NumPy 2.0.
  Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

  If you are a user of the module, the easiest solution will be to
  downgrade to 'numpy<2' or try to upgrade the affected module.
  We expect that some modules will need time to support NumPy 2.

  Traceback (most recent call last):  File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 415, in build_wheel
      return self._build_with_temp_dir(
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 10, in <module>
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/__init__.py", line 1477, in <module>
      from .functional import *  # noqa: F403
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/functional.py", line 9, in <module>
      import torch.nn.functional as F
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
      from .modules import *  # noqa: F403
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
      from .transformer import TransformerEncoder, TransformerDecoder, \
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
      device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
  /home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


  torch.__version__  = 2.2.2+cu121



  Compiling cuda extensions with
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2024 NVIDIA Corporation
  Built on Fri_Jun_14_16:34:21_PDT_2024
  Cuda compilation tools, release 12.6, V12.6.20
  Build cuda_12.6.r12.6/compiler.34431801_0
  from /usr/local/cuda/bin

  Traceback (most recent call last):
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 415, in build_wheel
      return self._build_with_temp_dir(
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 178, in <module>
    File "<string>", line 40, in check_cuda_torch_binary_vs_bare_metal
  RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 12.1.
  In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
  error: subprocess-exited-with-error
  
  × Building wheel for apex (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/assa8945/miniconda3/envs/opensora/bin/python /home/assa8945/miniconda3/envs/opensora/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpukfgekiy
  cwd: /tmp/pip-req-build-_blumxvs
  Building wheel for apex (pyproject.toml) ... error
  ERRO
R: Failed building wheel for apex
Failed to build apex
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (apex)
```

**Comment by lxrswdd** [comment]
Can anyone help?

**Comment by weijiawu** [comment]
@lxrswdd Hi, have you solved this issue?
