### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by Acedess** [hpcaitech/Open-Sora#685]
运行scripts/inference.py时遇到以下报错，有人遇到过吗？

Traceback (most recent call last):
  File "/home/wubinghao/Open-Sora/scripts/inference.py", line 304, in <module>
    main()
  File "/home/wubinghao/Open-Sora/scripts/inference.py", line 266, in main
    samples = scheduler.sample(
  File "/home/wubinghao/Open-Sora/opensora/schedulers/rf/__init__.py", line 52, in sample
    model_args = text_encoder.encode(prompts)
  File "/home/wubinghao/Open-Sora/opensora/models/text_encoder/t5.py", line 196, in encode
    caption_embs, emb_masks = self.t5.get_text_embeddings(text)
  File "/home/wubinghao/Open-Sora/opensora/models/text_encoder/t5.py", line 133, in get_text_embeddings
    text_encoder_embs = self.model(
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1980, in forward
    encoder_outputs = self.encoder(
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1115, in forward
    layer_outputs = layer_module(
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 695, in forward
    self_attention_outputs = self.layer[0](
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 602, in forward
    attention_output = self.SelfAttention(
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 521, in forward
    query_states = shape(self.q(hidden_states))  # (batch_size, n_heads, seq_length, dim_per_head)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wubinghao/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by chongjingup** [comment]
same problem
