### ISSUE TITLE
using llava get  caption,error

### ISSUE THREAD

**Issue by henbucuoshanghai** [hpcaitech/Open-Sora#728]
torchrun --nproc_per_node 1 --standalone -m tools.caption.caption_llava   ${ROOT_META}/meta_clips_info_fmin1_aes_aesmin4.csv   --dp-size 1   --tp-size 1   --model-path /home/ver/Open-Sora/llava_from_hf   --prompt video --num-workers 1 --bs 1

get error!

erate the video. The description should be no more than six sentences.
Data Parallel Rank 0:   0%|                                                                                                                | 0/7 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Data Parallel Rank 0:   0%|                                                                                                                | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home//anaconda3/envs/opensora/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home//anaconda3/envs/opensora/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home//Open-Sora/tools/caption/caption_llava.py", line 345, in <module>
    main(args)
  File "/anaconda3/envs/opensora/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home//Open-Sora/tools/caption/caption_llava.py", line 267, in main
    output_ids = super(type(model), model).generate(
  File "/home//anaconda3/envs/opensora/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/homr/anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/generation/utils.py", line 1527, in generate
    result = self._greedy_search(
  File "/home//anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/generation/utils.py", line 2411, in _greedy_search
    outputs = self(
  File "/home//anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home//anaconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'cache_position'
[2024-] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 68067) of binary: /home//anaconda3/envs/opensora/bin/python

**Comment by henbucuoshanghai** [comment]
tks

**Comment by Heng14** [comment]
maybe you could try to use transformers==4.37.2
