### ISSUE TITLE
Instruction from readme do not work

### ISSUE THREAD

**Issue by adamskrodzki** [hpcaitech/Open-Sora#729]
Hi 

I'm trying to install open-Sora on https://lightning.ai/

without success. 

I think problem is related to not all versions of dependencies being explicitly stated and therefore some dependency mismatch occures. 

Specific error while running gradle

```
 ~/Open-Sora python gradio/app.py                                        
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
  warnings.warn(
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/Open-Sora/gradio/app.py", line 171, in <module>
    from opensora.models.text_encoder.t5 import text_preprocessing
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/opensora/models/__init__.py", line 6, in <module>
    from .vae import *
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/opensora/models/vae/__init__.py", line 2, in <module>
    from .vae import VideoAutoencoderKL, VideoAutoencoderKLTemporalDecoder
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/opensora/models/vae/vae.py", line 5, in <module>
    from diffusers.models import AutoencoderKL, AutoencoderKLTemporalDecoder
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

also when building na image i can find :

THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md
    
    is this expected ?

**Comment by LuJingyi-John** [comment]
I meet same case. For a quick fix to the cached_download import error, you can modify the following file:
`/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py`
Simply remove `cached_download,` from the import line. The file should still work since this function is deprecated and not used in the current code.

**Comment by junjianren** [comment]
Let's take a look at the version downgrade of huggingface'hub. I have reduced it from 0.26.1 to 0.25.0, which solves the problem
