### ISSUE TITLE
ImportError: cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by mudasirkhanawan** [hpcaitech/Open-Sora#748]
I installed in WSL Ubuntu 24 and after successful installation when i run the command, it is giving error.
Please provide a way out to this error.

**python gradio/app.py**
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/huggingface_hub/__init__.py)

**Complete Error Logs**
-----------------------
`(opensora) ubuntu@DESKTOP-QM2667F:~/Open-Sora$ python gradio/app.py`
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ubuntu/Open-Sora/gradio/app.py", line 171, in <module>
    from opensora.models.text_encoder.t5 import text_preprocessing
  File "/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/__init__.py", line 6, in <module>
    from .vae import *
  File "/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/vae/__init__.py", line 2, in <module>
    from .vae import VideoAutoencoderKL, VideoAutoencoderKLTemporalDecoder
  File "/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py", line 5, in <module>
    from diffusers.models import AutoencoderKL, AutoencoderKLTemporalDecoder
  File "/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/ubuntu/miniconda3/envs/opensora/lib/python3.9/site-packages/huggingface_hub/__init__.py)

**Comment by mudasirkhanawan** [comment]
OK. That is fix. I installed below version.
`pip install --upgrade huggingface_hub==0.25.2`
