### ISSUE TITLE
Exception when running 'python gradio/app.py'

### ISSUE THREAD

**Issue by samihaddad99** [hpcaitech/Open-Sora#758]
The code is using an outdated module from huggingface_hub called _"cached_download"_

Below is the stack trace:

> (open-sora) c4@c4-ubuntu:~/Open-Sora$ python gradio/app.py
> /home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
>   _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
> /home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
>   warnings.warn(
> Traceback (most recent call last):
>   File "/home/c4/Open-Sora/gradio/app.py", line 171, in <module>
>     from opensora.models.text_encoder.t5 import text_preprocessing
>   File "/home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/opensora/models/__init__.py", line 6, in <module>
>     from .vae import *
>   File "/home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/opensora/models/vae/__init__.py", line 2, in <module>
>     from .vae import VideoAutoencoderKL, VideoAutoencoderKLTemporalDecoder
>   File "/home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/opensora/models/vae/vae.py", line 5, in <module>
>     from diffusers.models import AutoencoderKL, AutoencoderKLTemporalDecoder
>   File "/home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
>     from .utils import (
>   File "/home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 38, in <module>
>     from .dynamic_modules_utils import get_class_from_dynamic_module
>   File "/home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
>     from huggingface_hub import cached_download, hf_hub_download, model_info
> ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/c4/anaconda3/envs/open-sora/lib/python3.9/site-packages/huggingface_hub/__init__.py)

**Comment by samihaddad99** [comment]
Found a fix.

Edit the file calling the outdated reference:
code /home/<username>/anaconda3/envs/open-sora/lib/python3.9/site-packages/diffusers/utils/dynamic_modules_utils.py

On line 29;
Replace: `from huggingface_hub import cached_download, hf_hub_download, model_info`
With: `from huggingface_hub import hf_hub_download, model_info`

On line 287;
Replace: `resolved_module_file = cached_download(`
With: `resolved_module_file = hf_hub_download(`

re-run the `python gradio/app.py` command.

Side-note: _This was causing an error while I following the instructions on a fresh install of Ubuntu 22.04 LTS, so I thought it was worth inspecting. Nothing to do with the source code, but might help those that run into issues while installing dependencies._
