### ISSUE TITLE
apex needed

### ISSUE THREAD

**Issue by QingZhong1996** [hpcaitech/Open-Sora#761]
I have already used the following command for inference 
"python scripts/inference.py configs/opensora-v1-2/inference/sample.py \
  --num-frames 4s --resolution 720p \
  --layernorm-kernel False --flash-attn False \
  --prompt "a beautiful waterfall"", 
but I am still encountering an error requiring the installation of apex.

"Traceback (most recent call last):
  File "/./projects/Open-Sora/scripts/inference.py", line 304, in <module>
    main()
  File "//projects/Open-Sora/scripts/inference.py", line 289, in main
    save_path = save_sample(
  File "//myconda/envs/opensora/lib/python3.9/site-packages/opensora/datasets/utils.py", line 178, in save_sample
    write_video(save_path, x, fps=fps, video_codec="h264")
  File "//myconda/envs/opensora/lib/python3.9/site-packages/torchvision/io/video.py", line 132, in write_video
    frame.pict_type = "NONE"
  File "av/video/frame.pyx", line 193, in av.video.frame.VideoFrame.pict_type.__set__
TypeError: an integer is required
/myconda/envs/opensora/lib/python3.9/site-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_
node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
/myconda/envs/opensora/lib/python3.9/site-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
  warnings.warn(
/myconda/envs/opensora/lib/python3.9/site-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel
  warnings.warn("Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel")"

**Comment by rfww** [comment]
Hello, how to solve the issue of "TypeError: an integer is required"?

**Comment by Gracewx** [comment]
I encountered the same question when using this inference.

**Comment by Gracewx** [comment]
I encountered the same question when using this inference. I mean "TypeError: an integer is required"

**Comment by Gracewx** [comment]
> Hello, how to solve the issue of "TypeError: an integer is required"?

The TypeError was solved when I changed the Line132 "frame.pict_type = "NONE"" into "frame.pict_type = 1" in the function named "write_video". The function is in "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torchvision/io/video.py".

**Comment by Gracewx** [comment]
> Hello, how to solve the issue of "TypeError: an integer is required"?

The TypeError was solved when I changed the Line132 "frame.pict_type = "NONE"" into "frame.pict_type = 1" in the function named "write_video". The function is in "/opt/conda/envs/pytorch/lib/python3.10/site-packages/torchvision/io/video.py". 

Hope this helps~

**Comment by QingZhong1996** [comment]
solved by downgrade av to av-12.0.0 @rfww @Gracewx
